FROM python:3.10

# Dependencies
RUN pip3 install pandas
RUN pip3 install flask
RUN pip3 install flask_sqlalchemy
RUN pip3 install psycopg2

# Copy the current directory contents into the container at /app
# While ignoring the large CSV in the .dockerignore
COPY . /app
# Set the working directory to /app
WORKDIR /app

# Expose the Flask port
EXPOSE 8080

# run the webserver
CMD ["python3", "data.py"]