FROM python:3.8-slim-buster

# Dependencies
RUN apt-get update && apt-get -y install build-essential \
    && apt-get -y install libpq-dev python3-dev
RUN pip3 install flask
RUN pip3 install pandas
RUN pip3 install psycopg2-binary
# Copy the current directory contents into the container at /app
# While ignoring the large CSV in the .dockerignore
COPY . /app
# Set the working directory to /app
WORKDIR /app

# Expose the Flask port
EXPOSE 8080

# run the webserver
CMD ["python3", "data.py"]