FROM python:3.8-slim-buster

# Dependencies
RUN pip3 install --upgrade pip
RUN pip3 freeze requirements.txt

# Copy the current directory contents into the container at /app
# While ignoring the large CSV in the .dockerignore
COPY . /app
# Set the working directory to /app
WORKDIR /app

# Expose the Flask port
EXPOSE 8080

# run the webserver
CMD ["python3", "data.py"]